# Configuration for the Azure Cycle Cloud platform.

# yamllint disable rule:anchors rule:line-length

app:
  gpu:
    batchargs: &gpu-batchargs
      nodes: 1
      partition: gpu
  launcher: srun --export=ALL
  partitions:
    netaccess: htc
  platform: &platform
    account: epic
    scheduler: slurm
zarrs:
  common:
    execution:
      batchargs:
        cores: 1
        walltime: '00:20:00'
        --mem-per-cpu: 6G
      mpiargs:
        - "--export=ALL"
ufs2arco:
  mover:
    name: datamover
    batch_size: 1
