common: &common
  nodes: 1:ppn=1
  walltime: 00:10:00
  account: '{{ app.platform.account }}'
  partition: '{{ app.partitions.compute }}'
  queue: '{{ app.queues.batch }}'
  command: 'make {{ jobname }} config=eagle.yaml'
  join: '{{ app.base }}/{{ app.platform.scheduler }}/{{ jobname }}.{{ app.platform.scheduler }}'
common_netaccess: &common_netaccess
  <<: *common
  partition: '{{ app.partitions.netaccess }}'
common_gpu: &common_gpu
  <<: *common
  partition: '{{ app.gpu.batchargs.partition }}'
  queue: '{{ app.gpu.batchargs.queue }}'
  native: '{{ app.gpu.batchargs.native }}'
command_nobatch: &command_nobatch 'make {{ jobname }} config=eagle.yaml batch=false'
workflow:
  attrs:
    realtime: false
    scheduler: '{{ app.platform.scheduler }}'
  cycledef: 
    - attrs: 
        group: cyc
      spec: '{{ app.time.inference_start.strftime("%Y%m%d%H%M") }} {{ app.time.inference_start.strftime("%Y%m%d%H%M") }} 06:00:00'
  log:
    value:
      cyclestr:
        value: '{{ app.base }}/{{ app.platform.scheduler }}/rocoto.@Y@m@d@H.{{ app.platform.scheduler }}'
  tasks:
    task_grids_and_meshes:
      <<: *common_netaccess
      jobname: grids-and-meshes
      command: *command_nobatch
    task_zarr_gfs:
      <<: *common_netaccess
      jobname: zarr-gfs
      command: *command_nobatch
      memory: '{{ zarrs.common.execution.batchargs.memory }}'
      dependency:
        taskdep_grids_and_meshes:
          attrs:
            task: grids_and_meshes
    task_zarr_hrrr:
      <<: *common_netaccess
      jobname: zarr-hrrr
      command: *command_nobatch
      memory:  '{{ zarrs.common.execution.batchargs.memory }}'
      dependency:
        taskdep_grids_and_meshes:
          attrs: 
            task: grids_and_meshes
    task_training:
      <<: *common_gpu
      jobname: training
      command: *command_nobatch
      dependency:
        and:
          datadep_zarr_gfs:
            value: 'run/{{ app.experiment_name }}/data/runscript.zarr-gfs.done'
          datadep_zarr_hrrr:
            value: 'run/{{ app.experiment_name }}/data/runscript.zarr-hrrr.done'
    task_inference:
      <<: *common_gpu
      jobname: inference
      command: *command_nobatch
      dependency:
          datadep_training:
            value: 'run/{{ app.experiment_name }}/training/runscript.training.done'
    metatask_vx:
      var:
        extent: global global lam lam
        metric: grid obs grid obs
      task_vx_#metric#_#extent#:
        <<: *common_netaccess
        jobname: vx-#metric#-#extent#
        command: *command_nobatch
        dependency:
          datadep_inference:
            value: 'run/{{ app.experiment_name }}/inference/runscript.inference.done'
    metatask_vis:
      var:
        extent: global global lam lam
        metric: grid obs grid obs 
      task_vis_#metric#_#extent#:
        <<: *common
        jobname: vis-#metric#-#extent#
        command: *command_nobatch
        dependency:
          datadep_inference:
            value: 'run/{{ app.experiment_name }}/inference/runscript.inference.done'
