# Configuration for the NOAA RDHPCS Ursa platform.

# yamllint disable rule:anchors rule:line-length

app:
  gpu:
    batchargs: &gpu-batchargs
      --gres: 'gpu:h100:1'
      nodes: 1
      partition: u1-h100
      queue: gpuwf
  launcher: srun --export=ALL
  partitions:
    netaccess: u1-service
  platform: &platform
    account: epic
    scheduler: slurm
inference:
  execution:
    envcmds: # PM DRY THIS OUT
      - source /etc/profile.d/profile-slurm.sh
      - source {{ val.conda }}/etc/profile.d/conda.sh
      - conda activate anemoi
      - set -ex
training:
  execution:
    envcmds: # PM DRY THIS OUT
      - source /etc/profile.d/profile-slurm.sh
      - source {{ val.conda }}/etc/profile.d/conda.sh
      - conda activate anemoi
      - set -ex
      - export SLURM_GPUS_PER_NODE=1
      - export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
zarrs:
  common:
    execution:
      batchargs:
        --mem-per-cpu: 3G
      envcmds: !list '{{ ["source /etc/profile.d/profile-slurm.sh"] + zarrs.common.envcmds }}'
      mpiargs:
        - "--export=ALL"
