name: Code Quality Checks
on:
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - synchronize
  workflow_dispatch:
    branches:
      - '**'
jobs:
  code-quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
      - name: Restore Conda
        uses: actions/cache/restore@v5
        with:
          path: src/conda
          key: ${{ runner.os }}-conda-${{ github.event.pull_request.number }}
      - name: Build Runtime Environment
        run: time make -C src devenv cudascript=dummy
      - name: Cache Conda
        uses: actions/cache/save@v5
        with:
          path: src/conda
          key: ${{ runner.os }}-conda-${{ github.event.pull_request.number }}
      - name: Check Formatting
        run: |
          make -C src format
          if [[ -n "$(git status --porcelain)" ]]; then
            git --no-pager diff
            echo UNFORMATTED CODE DETECTED
            exit 1
          fi
          echo NO FORMATTING ISSUES DETECTED
      - name: Run Python Linter
        run: make -C src lint
      - name: Run Shell Checker
        run: make -C src shellcheck
      - name: Run Python Typechecker
        run: make -C src typecheck
      - name: Run YAML Linter
        run: make -C src yamllint
