name: Code Quality Checks
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
  workflow_dispatch:
    branches:
      - '**'
jobs:
  code-quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
        with:
          clean: false
#       - name: Restore Caches Conda Installation
#         uses: actions/cache@v4
#         with:
#           path: src/conda
#           key: ${{ runner.os }}-conda-${{ github.event.pull_request.head.sha }}
      - name: Build Runtime Environment
        run: time make -C src devenv cudascript=dummy
      - name: Cache Conda Installation
        uses: actions/cache/save@v5
        with:
          path: src/conda
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Check Formatting
        run: |
          make -C src format
          if [[ -n "$(git status --porcelain)" ]]; then
            git --no-pager diff
            echo UNFORMATTED CODE DETECTED
            exit 1
          fi
